# # CREATE A NEW course
# POST http://localhost:8080/api/v1/courses
# Content-Type: application/json

# {
#       "title": "Introduction to English",
#       "creditUnit": 2,
#       "code": "GST 101",
#       "description": "Description for use of English"
# }


# # GET ALL course
# GET http://localhost:8080/api/v1/courses
# Content-Type: application/json



# # GET course BY ID
# GET http://localhost:8080/api/v1/courses/1
# Content-Type: application/json



# # UPDATE course BY ID
PUT http://localhost:8080/api/v1/courses/1
Content-Type: application/json

 {
      "title": "Introduction to English 2",
      "creditUnit": 2,
      "code": "GST 102",
      "description": "Description for use of English 2"
}



# # DELETE course BY ID
# DELETE http://localhost:8080/api/v1/course/1
# Content-Type: application/json
