# # CREATE A NEW STAFF
# POST http://localhost:8080/api/v1/staff
# Content-Type: application/json

# {
#       "firstName": "emeka",
#       "lastName": "Anyim",
#       "phoneNumber": 9023212125,
#       "email": "emekaanyim@gmail.com",
#       "salary": 150000,
#       "course": "CSC 201"
# }


# # GET ALL STAFF
# GET http://localhost:8080/api/v1/staff
# Content-Type: application/json



# # GET STAFF BY ID
# GET http://localhost:8080/api/v1/staff/1
# Content-Type: application/json



# # UPDATE STAFF BY ID
PUT http://localhost:8080/api/v1/staff/102
Content-Type: application/json

{
      "firstName": "emeka",
      "lastName": "Anyim",
      "phoneNumber": 9023212125,
      "email": "emekaanyim@gmail.com",
      "salary": 150000,
      "course": "CSC 201"
}



# # DELETE STAFF BY ID
# DELETE http://localhost:8080/api/v1/staff/1
# Content-Type: application/json
